# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhiWG46FORWIxfAXVcWv-pphKtIQ8Z4d
"""

# app.py
import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold

# --- Page Configuration ---
st.set_page_config(page_title="Alt-Data Market Insight Agent", layout="wide")

# --- Sidebar Configuration ---
st.sidebar.title("⚙️ Engine Settings")
st.sidebar.markdown("Configure the parameters for the market analysis engine.")

# Interactive Widgets for user input
ticker = st.sidebar.text_input("Target Asset (Ticker)", value="IVV")
start_date = st.sidebar.date_input("Start Date", pd.to_datetime("2020-01-01"))
end_date = st.sidebar.date_input("End Date", pd.to_datetime("2023-12-31"))
n_splits = st.sidebar.slider("K-Fold Splits", min_value=3, max_value=10, value=5)

# --- Core Logic & Caching ---
# @st.cache_data ensures we don't re-download data every time the user tweaks a slider
@st.cache_data
def load_and_engineer_data(t, start, end):
    try:
        df = yf.download(t, start=start, end=end, progress=False)
        if df.empty:
            return None

        # Feature Engineering
        df['Return'] = df['Close'].pct_change()
        df['Target'] = np.where(df['Return'].shift(-1) > 0, 1, 0)
        df['SMA_10'] = df['Close'].rolling(window=10).mean()
        df['Momentum_5'] = df['Close'] - df['Close'].shift(5)
        df = df.dropna()
        return df
    except Exception as e:
        return None

# --- Main Dashboard ---
st.title("📈 Alt-Data Market Insight Agent")
st.markdown("""
This dashboard evaluates the predictive power of traditional technical indicators
using K-Fold cross-validation, while integrating Alternative Data (Social Sentiment)
for holistic risk assessment.
""")

st.divider()

# --- Module 1: Traditional Finance & K-Fold Validation ---
st.header(f"1. Feature Validation: {ticker}")

with st.spinner(f"Fetching data and engineering features for {ticker}..."):
    df = load_and_engineer_data(ticker, start_date, end_date)

if df is not None:
    col1, col2 = st.columns([1, 2])

    with col1:
        st.subheader("Raw Data Preview")
        st.dataframe(df[['Close', 'SMA_10', 'Momentum_5', 'Target']].tail())

    with col2:
        st.subheader(f"{n_splits}-Fold Cross Validation Correlation")
        kf = KFold(n_splits=n_splits, shuffle=False)
        results = []

        for train_idx, test_idx in kf.split(df):
            train_data = df.iloc[train_idx]
            corr_sma = train_data['SMA_10'].corr(train_data['Target'])
            corr_mom = train_data['Momentum_5'].corr(train_data['Target'])
            results.append([corr_sma, corr_mom])

        res_df = pd.DataFrame(results, columns=['Corr_SMA_10', 'Corr_Momentum_5'])
        res_df.index = [f'Fold_{i+1}' for i in range(len(res_df))]

        # Plotting
        fig, ax = plt.subplots(figsize=(8, 4))
        res_df.plot(kind='bar', ax=ax)
        ax.set_ylabel('Pearson Correlation')
        ax.axhline(0, color='black', linewidth=0.8, linestyle='--')
        plt.xticks(rotation=0)
        st.pyplot(fig) # Render matplotlib figure in Streamlit

else:
    st.error("Failed to fetch data. Please check the ticker symbol or date range.")

st.divider()

# --- Module 2: Alternative Data EDA ---
st.header("2. Alternative Data (Leading Indicators)")
st.markdown("Analyzing non-structured market psychology metrics (e.g., Social Media Sentiment).")

# Simulating Alternative Data
dates = pd.date_range(start=start_date, end=end_date, freq='D')
np.random.seed(42)
alt_df = pd.DataFrame({
    'Date': dates,
    'Sentiment_Score': np.random.normal(loc=0.5, scale=0.2, size=len(dates)),
    'Mention_Volume': np.random.randint(1000, 50000, size=len(dates))
}).set_index('Date')

# Dual-axis plotting
fig2, ax1 = plt.subplots(figsize=(12, 5))
ax1.plot(alt_df.index, alt_df['Sentiment_Score'], color='#1f77b4', label='Sentiment')
ax1.set_ylabel('Sentiment Score', color='#1f77b4')
ax1.tick_params(axis='y', labelcolor='#1f77b4')

ax2 = ax1.twinx()
ax2.bar(alt_df.index, alt_df['Mention_Volume'], color='gray', alpha=0.3, label='Volume')
ax2.set_ylabel('Mention Volume', color='gray')
ax2.tick_params(axis='y', labelcolor='gray')

plt.title('Simulated Alternative Data: Sentiment vs. Volume')
st.pyplot(fig2)

st.sidebar.divider()
st.sidebar.info("Developed as a conceptual prototype for automated quantitative analysis workflows.")